-- Samsung Event Dashboard collaboration layer v1
-- Run in Supabase SQL Editor as a project owner.
-- Safe to run repeatedly. Never execute this file with a browser key.

begin;

create schema if not exists dashboard_private;
revoke all on schema dashboard_private from public, anon, authenticated;

create table if not exists public.dashboard_events (
  event_id text primary key,
  label text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_members (
  event_id text not null references public.dashboard_events(event_id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('viewer', 'editor')),
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table if not exists public.workstream_updates (
  event_id text not null references public.dashboard_events(event_id) on delete cascade,
  workstream_id text not null,
  baseline_status text,
  baseline_due_date date,
  baseline_owner text,
  status text,
  due_date date,
  owner text,
  status_set boolean not null default false,
  due_date_set boolean not null default false,
  owner_set boolean not null default false,
  version bigint not null default 1 check (version > 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (event_id, workstream_id),
  constraint workstream_status_valid check (
    status is null or status in (
      'Not Started', 'In Progress', 'Internal Review', 'HQ Review',
      'Pending Approval', 'Pending Review', 'Confirmed', 'In Production',
      'Completed', 'Blocked', 'Needs Update', 'Not Applicable'
    )
  )
);

create table if not exists public.stage_updates (
  event_id text not null references public.dashboard_events(event_id) on delete cascade,
  workstream_id text not null,
  stage_id text not null,
  baseline_status text,
  baseline_due_date date,
  baseline_owner text,
  baseline_completed_date date,
  status text,
  due_date date,
  owner text,
  completed_date date,
  status_set boolean not null default false,
  due_date_set boolean not null default false,
  owner_set boolean not null default false,
  completed_date_set boolean not null default false,
  version bigint not null default 1 check (version > 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (event_id, workstream_id, stage_id),
  constraint stage_status_valid check (
    status is null or status in ('Not Started', 'In Progress', 'Pending Review', 'Completed', 'Blocked')
  )
);

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  event_id text not null,
  entity_type text not null check (entity_type in ('workstream', 'stage')),
  workstream_id text not null,
  stage_id text,
  field_name text not null check (field_name in ('status', 'due_date', 'owner', 'completed_date')),
  old_value text,
  new_value text,
  changed_by uuid not null references auth.users(id) on delete restrict,
  changed_at timestamptz not null default now()
);

create table if not exists public.document_files (
  event_id text not null references public.dashboard_events(event_id) on delete cascade,
  document_id text not null,
  bucket_id text not null default 'event-files',
  object_path text not null,
  file_name text not null,
  created_at timestamptz not null default now(),
  primary key (event_id, document_id),
  unique (bucket_id, object_path)
);

create index if not exists event_members_user_idx on public.event_members(user_id, event_id);
create index if not exists workstream_updates_event_idx on public.workstream_updates(event_id);
create index if not exists stage_updates_event_idx on public.stage_updates(event_id);
create index if not exists change_history_event_idx on public.change_history(event_id, changed_at desc);
create index if not exists document_files_object_idx on public.document_files(bucket_id, object_path);

create or replace function dashboard_private.is_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select is_admin from public.profiles where user_id = p_user_id), false);
$$;

create or replace function dashboard_private.event_role(p_event_id text, p_user_id uuid default auth.uid())
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case
    when dashboard_private.is_admin(p_user_id) then 'admin'
    else coalesce((
      select role from public.event_members
      where event_id = p_event_id and user_id = p_user_id
    ), '')
  end;
$$;

create or replace function dashboard_private.can_download(p_event_id text, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select dashboard_private.event_role(p_event_id, p_user_id) in ('viewer', 'editor', 'admin');
$$;

create or replace function dashboard_private.can_edit(p_event_id text, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select dashboard_private.event_role(p_event_id, p_user_id) in ('editor', 'admin');
$$;

create or replace function dashboard_private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (user_id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', ''), '')
  )
  on conflict (user_id) do update
    set email = excluded.email,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function dashboard_private.handle_new_user();

insert into public.profiles (user_id, email, display_name)
select
  u.id,
  coalesce(u.email, ''),
  nullif(coalesce(u.raw_user_meta_data ->> 'display_name', u.raw_user_meta_data ->> 'full_name', ''), '')
from auth.users u
on conflict (user_id) do update
set email = excluded.email,
    updated_at = now();

create or replace function public.get_public_dashboard_updates(p_event_id text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'workstreams', coalesce((
      select jsonb_agg(jsonb_build_object(
        'workstream_id', w.workstream_id,
        'status', w.status,
        'due_date', w.due_date,
        'owner', w.owner,
        'status_set', w.status_set,
        'due_date_set', w.due_date_set,
        'owner_set', w.owner_set,
        'version', w.version,
        'updated_at', w.updated_at,
        'updated_by_name', coalesce(nullif(p.display_name, ''), 'Member')
      ) order by w.workstream_id)
      from public.workstream_updates w
      left join public.profiles p on p.user_id = w.updated_by
      where w.event_id = p_event_id
    ), '[]'::jsonb),
    'stages', coalesce((
      select jsonb_agg(jsonb_build_object(
        'workstream_id', s.workstream_id,
        'stage_id', s.stage_id,
        'status', s.status,
        'due_date', s.due_date,
        'owner', s.owner,
        'completed_date', s.completed_date,
        'status_set', s.status_set,
        'due_date_set', s.due_date_set,
        'owner_set', s.owner_set,
        'completed_date_set', s.completed_date_set,
        'version', s.version,
        'updated_at', s.updated_at,
        'updated_by_name', coalesce(nullif(p.display_name, ''), 'Member')
      ) order by s.workstream_id, s.stage_id)
      from public.stage_updates s
      left join public.profiles p on p.user_id = s.updated_by
      where s.event_id = p_event_id
    ), '[]'::jsonb)
  );
$$;

create or replace function public.get_my_dashboard_access()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case when auth.uid() is null then
    jsonb_build_object('global_role', '', 'event_roles', '{}'::jsonb)
  else jsonb_build_object(
    'global_role', case when dashboard_private.is_admin(auth.uid()) then 'admin' else '' end,
    'event_roles', coalesce((
      select jsonb_object_agg(event_id, role)
      from public.event_members
      where user_id = auth.uid()
    ), '{}'::jsonb)
  ) end;
$$;

create or replace function public.update_workstream_overlay(
  p_event_id text,
  p_workstream_id text,
  p_expected_version bigint,
  p_status text,
  p_due_date date,
  p_owner text,
  p_status_set boolean,
  p_due_date_set boolean,
  p_owner_set boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.workstream_updates%rowtype;
  v_old_status text;
  v_old_due text;
  v_old_owner text;
begin
  if auth.uid() is null or not dashboard_private.can_edit(p_event_id, auth.uid()) then
    raise exception 'EDIT_NOT_AUTHORIZED' using errcode = '42501';
  end if;
  if p_status_set and (p_status is null or p_status not in (
    'Not Started', 'In Progress', 'Internal Review', 'HQ Review',
    'Pending Approval', 'Pending Review', 'Confirmed', 'In Production',
    'Completed', 'Blocked', 'Needs Update', 'Not Applicable'
  )) then
    raise exception 'INVALID_STATUS' using errcode = '22023';
  end if;

  select * into v_row from public.workstream_updates
  where event_id = p_event_id and workstream_id = p_workstream_id
  for update;
  if not found then raise exception 'UNKNOWN_WORKSTREAM' using errcode = '22023'; end if;
  if v_row.version <> p_expected_version then
    raise exception 'COLLAB_CONFLICT' using errcode = '40001';
  end if;

  v_old_status := case when v_row.status_set then v_row.status else v_row.baseline_status end;
  v_old_due := (case when v_row.due_date_set then v_row.due_date else v_row.baseline_due_date end)::text;
  v_old_owner := case when v_row.owner_set then v_row.owner else v_row.baseline_owner end;

  update public.workstream_updates set
    status = case when p_status_set then p_status else status end,
    due_date = case when p_due_date_set then p_due_date else due_date end,
    owner = case when p_owner_set then p_owner else owner end,
    status_set = status_set or p_status_set,
    due_date_set = due_date_set or p_due_date_set,
    owner_set = owner_set or p_owner_set,
    version = version + 1,
    updated_at = now(),
    updated_by = auth.uid()
  where event_id = p_event_id and workstream_id = p_workstream_id
  returning * into v_row;

  if p_status_set and v_old_status is distinct from p_status then
    insert into public.change_history(event_id, entity_type, workstream_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'workstream', p_workstream_id, 'status', v_old_status, p_status, auth.uid());
  end if;
  if p_due_date_set and v_old_due is distinct from p_due_date::text then
    insert into public.change_history(event_id, entity_type, workstream_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'workstream', p_workstream_id, 'due_date', v_old_due, p_due_date::text, auth.uid());
  end if;
  if p_owner_set and v_old_owner is distinct from p_owner then
    insert into public.change_history(event_id, entity_type, workstream_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'workstream', p_workstream_id, 'owner', v_old_owner, p_owner, auth.uid());
  end if;

  return jsonb_build_object('version', v_row.version, 'updated_at', v_row.updated_at);
end;
$$;

create or replace function public.update_stage_overlay(
  p_event_id text,
  p_workstream_id text,
  p_stage_id text,
  p_expected_version bigint,
  p_status text,
  p_due_date date,
  p_owner text,
  p_status_set boolean,
  p_due_date_set boolean,
  p_owner_set boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.stage_updates%rowtype;
  v_old_status text;
  v_old_due text;
  v_old_owner text;
  v_old_completed text;
  v_new_completed date;
  v_completed_set boolean;
begin
  if auth.uid() is null or not dashboard_private.can_edit(p_event_id, auth.uid()) then
    raise exception 'EDIT_NOT_AUTHORIZED' using errcode = '42501';
  end if;
  if p_status_set and (p_status is null or p_status not in ('Not Started', 'In Progress', 'Pending Review', 'Completed', 'Blocked')) then
    raise exception 'INVALID_STAGE_STATUS' using errcode = '22023';
  end if;

  select * into v_row from public.stage_updates
  where event_id = p_event_id and workstream_id = p_workstream_id and stage_id = p_stage_id
  for update;
  if not found then raise exception 'UNKNOWN_STAGE' using errcode = '22023'; end if;
  if v_row.version <> p_expected_version then
    raise exception 'COLLAB_CONFLICT' using errcode = '40001';
  end if;

  v_old_status := case when v_row.status_set then v_row.status else v_row.baseline_status end;
  v_old_due := (case when v_row.due_date_set then v_row.due_date else v_row.baseline_due_date end)::text;
  v_old_owner := case when v_row.owner_set then v_row.owner else v_row.baseline_owner end;
  v_old_completed := (case when v_row.completed_date_set then v_row.completed_date else v_row.baseline_completed_date end)::text;
  v_completed_set := v_row.completed_date_set;
  v_new_completed := v_row.completed_date;
  if p_status_set and p_status = 'Completed' and v_old_status is distinct from 'Completed' then
    v_new_completed := current_date;
    v_completed_set := true;
  elsif p_status_set and p_status <> 'Completed' and v_old_status = 'Completed' then
    v_new_completed := null;
    v_completed_set := true;
  end if;

  update public.stage_updates set
    status = case when p_status_set then p_status else status end,
    due_date = case when p_due_date_set then p_due_date else due_date end,
    owner = case when p_owner_set then p_owner else owner end,
    completed_date = v_new_completed,
    status_set = status_set or p_status_set,
    due_date_set = due_date_set or p_due_date_set,
    owner_set = owner_set or p_owner_set,
    completed_date_set = v_completed_set,
    version = version + 1,
    updated_at = now(),
    updated_by = auth.uid()
  where event_id = p_event_id and workstream_id = p_workstream_id and stage_id = p_stage_id
  returning * into v_row;

  if p_status_set and v_old_status is distinct from p_status then
    insert into public.change_history(event_id, entity_type, workstream_id, stage_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'stage', p_workstream_id, p_stage_id, 'status', v_old_status, p_status, auth.uid());
  end if;
  if p_due_date_set and v_old_due is distinct from p_due_date::text then
    insert into public.change_history(event_id, entity_type, workstream_id, stage_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'stage', p_workstream_id, p_stage_id, 'due_date', v_old_due, p_due_date::text, auth.uid());
  end if;
  if p_owner_set and v_old_owner is distinct from p_owner then
    insert into public.change_history(event_id, entity_type, workstream_id, stage_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'stage', p_workstream_id, p_stage_id, 'owner', v_old_owner, p_owner, auth.uid());
  end if;
  if v_old_completed is distinct from v_row.completed_date::text then
    insert into public.change_history(event_id, entity_type, workstream_id, stage_id, field_name, old_value, new_value, changed_by)
    values (p_event_id, 'stage', p_workstream_id, p_stage_id, 'completed_date', v_old_completed, v_row.completed_date::text, auth.uid());
  end if;

  return jsonb_build_object('version', v_row.version, 'updated_at', v_row.updated_at, 'completed_date', v_row.completed_date);
end;
$$;

create or replace function public.get_document_file(p_event_id text, p_document_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare v_file public.document_files%rowtype;
begin
  if auth.uid() is null or not dashboard_private.can_download(p_event_id, auth.uid()) then
    raise exception 'DOWNLOAD_NOT_AUTHORIZED' using errcode = '42501';
  end if;
  select * into v_file from public.document_files
  where event_id = p_event_id and document_id = p_document_id;
  if not found then raise exception 'DOCUMENT_NOT_MIGRATED' using errcode = '22023'; end if;
  return jsonb_build_object(
    'bucket_id', v_file.bucket_id,
    'object_path', v_file.object_path,
    'file_name', v_file.file_name
  );
end;
$$;

alter table public.dashboard_events enable row level security;
alter table public.profiles enable row level security;
alter table public.event_members enable row level security;
alter table public.workstream_updates enable row level security;
alter table public.stage_updates enable row level security;
alter table public.change_history enable row level security;
alter table public.document_files enable row level security;

drop policy if exists dashboard_events_public_read on public.dashboard_events;
create policy dashboard_events_public_read on public.dashboard_events
for select to anon, authenticated using (true);

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
for select to authenticated using (user_id = auth.uid() or dashboard_private.is_admin(auth.uid()));

drop policy if exists event_members_self_read on public.event_members;
create policy event_members_self_read on public.event_members
for select to authenticated using (user_id = auth.uid() or dashboard_private.is_admin(auth.uid()));

drop policy if exists workstream_member_read on public.workstream_updates;
create policy workstream_member_read on public.workstream_updates
for select to authenticated using (dashboard_private.can_download(event_id, auth.uid()));

drop policy if exists stage_member_read on public.stage_updates;
create policy stage_member_read on public.stage_updates
for select to authenticated using (dashboard_private.can_download(event_id, auth.uid()));

drop policy if exists history_editor_read on public.change_history;
create policy history_editor_read on public.change_history
for select to authenticated using (dashboard_private.can_edit(event_id, auth.uid()));

drop policy if exists document_member_read on public.document_files;
create policy document_member_read on public.document_files
for select to authenticated using (dashboard_private.can_download(event_id, auth.uid()));

revoke all on public.profiles, public.event_members, public.workstream_updates, public.stage_updates, public.change_history, public.document_files from anon;
grant select on public.dashboard_events to anon, authenticated;
grant select on public.profiles, public.event_members, public.workstream_updates, public.stage_updates, public.change_history, public.document_files to authenticated;
revoke all on function public.get_public_dashboard_updates(text) from public;
revoke all on function public.get_my_dashboard_access() from public;
revoke all on function public.update_workstream_overlay(text,text,bigint,text,date,text,boolean,boolean,boolean) from public;
revoke all on function public.update_stage_overlay(text,text,text,bigint,text,date,text,boolean,boolean,boolean) from public;
revoke all on function public.get_document_file(text,text) from public;
grant execute on function public.get_public_dashboard_updates(text) to anon, authenticated;
grant execute on function public.get_my_dashboard_access() to authenticated;
grant execute on function public.update_workstream_overlay(text,text,bigint,text,date,text,boolean,boolean,boolean) to authenticated;
grant execute on function public.update_stage_overlay(text,text,text,bigint,text,date,text,boolean,boolean,boolean) to authenticated;
grant execute on function public.get_document_file(text,text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('event-files', 'event-files', false, 52428800, array['application/pdf'])
on conflict (id) do update set public = false;

drop policy if exists event_file_member_download on storage.objects;
create policy event_file_member_download on storage.objects
for select to authenticated
using (
  bucket_id = 'event-files'
  and exists (
    select 1 from public.document_files d
    where d.bucket_id = storage.objects.bucket_id
      and d.object_path = storage.objects.name
      and dashboard_private.can_download(d.event_id, auth.uid())
  )
);

do $$
begin
  alter publication supabase_realtime add table public.workstream_updates;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.stage_updates;
exception when duplicate_object then null;
end $$;

commit;
